version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.17.6
    container_name: elasticsearch
    environment:
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - discovery.type=single-node
      - cluster.name=es-docker
      - node.name=node1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    # mem_limit: 4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - test

  mongo0:
    image: mongo:4.4
    container_name: mongo0
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - ./rs-init.sh:/scripts/rs-init.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - test

  kibana:
    container_name: kibana
    image: kibana:7.17.6
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - 5601:5601
    networks:
      - test
    depends_on:
      - elasticsearch

  monstache-profile:
    image: rwynn/monstache:6.7.10
    container_name: monstacheprofile
    working_dir: /app
    command: -f ./monstache_profile.config.toml
    volumes:
      - ./monstache_profile.config.toml:/app/monstache_profile.config.toml
    depends_on:
      - elasticsearch
      - mongo0
    ports:
      - "8080:8080"
    networks:
      - test
    healthcheck:
      test: "wget -q -O - http://localhost:8080/healthz"
      interval: 10s
      timeout: 30s
      retries: 300
    restart: unless-stopped

  monstache-tags:
    image: rwynn/monstache:6.7.10
    container_name: monstachetags
    working_dir: /app
    command: -f ./monstache_tags.config.toml
    volumes:
      - ./monstache_tags.config.toml:/app/monstache_tags.config.toml
    depends_on:
      - elasticsearch
      - mongo0
    ports:
      - "8081:8080"
    networks:
      - test
    healthcheck:
      test: "wget -q -O - http://localhost:8080/healthz"
      interval: 10s
      timeout: 30s
      retries: 300
    restart: unless-stopped

volumes:
  elasticsearch-data:
    driver: local

networks:
  test:
    driver: bridge